### ISSUE TITLE
Can I flash this to an eMMC module?

### ISSUE THREAD

**Issue by arjan-kuiper** [Qengineering/Jetson-Nano-Ubuntu-20-image#10]
As the title states, I have a Jetson Nano module with 16GB of eMMC memory instead of an SD card slot. Is it somehow possible to flash this image into memory either with or without NVIDIA's SDKManager?

**Comment by Qengineering** [comment]
I'm afraid, it's not possible. Best to follow the instructions at our site [Ubuntu 20.04](https://qengineering.eu/install-ubuntu-20.04-on-jetson-nano.html) to upgrade the OS manually.

**Comment by arjan-kuiper** [comment]
> I'm afraid, it's not possible. Best to follow the instructions at our site [Ubuntu 20.04](https://qengineering.eu/install-ubuntu-20.04-on-jetson-nano.html) to upgrade the OS manually.

I've done like you said and it worked like a charm. Thank you very much!
