### ISSUE TITLE
couldn't identify type of root file system for fsck hook while upgrading to Ubuntu 20.04

### ISSUE THREAD

**Issue by N0rma1zz** [Qengineering/Jetson-Nano-Ubuntu-20-image#100]
![6f0eb923f7ec63247e4880746a73b0a0](https://github.com/user-attachments/assets/7f394fa6-095a-49ea-8c90-7a9efccbcb31)

**Comment by Qengineering** [comment]
It's a harmless warning. 
I had it from the very first version.

**Comment by N0rma1zz** [comment]
it stopped after i pressed [enter].i reboot and my system got wrong

**Comment by Qengineering** [comment]
Somehow your upgrade failed. It is hard to say where it went wrong.
It can be some third-party software upgrading itself, or some unintended dependency giving troubles.
Most important, stick to Ubuntu 20.04. Do not upgrade to later releases, even as Ubuntu asked.
The only advise left, is starting all over again, with a fresh image.
