### ISSUE TITLE
img is not complete?

### ISSUE THREAD

**Issue by DarrenSong** [Qengineering/Jetson-Nano-Ubuntu-20-image#101]
![image](https://github.com/user-attachments/assets/d331ce12-36a1-4aee-9d8d-429ecd7214bb)

**Comment by DarrenSong** [comment]
yes, it seem like same with you
![image](https://github.com/user-attachments/assets/8d1a2b83-5f2a-4f0d-91ef-f6cc66ba697c)

**Comment by DarrenSong** [comment]
maybe there is no enough space in my C drive?

**Comment by Qengineering** [comment]
That's always a possibility.
A good Etcher alternative can be the [Raspberry Pi Imager](https://www.raspberrypi.com/software/).

**Comment by DarrenSong** [comment]
now it is ok,thank yo so much

**Comment by clankill3r** [comment]
I had something simulair:

<img width="912" height="592" alt="Image" src="https://github.com/user-attachments/assets/a9f57b3e-a3c3-4571-bc8d-2d2051056a0a" />

Using the Raspberry Pi Imager solved the problem for me.
