### ISSUE TITLE
Can not download image from sync.com

### ISSUE THREAD

**Issue by mishabeliy15** [Qengineering/Jetson-Nano-Ubuntu-20-image#44]
Hey!
I'm very glad to see your image that already have everything I need.
But I can't download it.

https://github.com/Qengineering/Jetson-Nano-Ubuntu-20-image/assets/25367184/767c38e8-1ee9-4914-bd38-45459ee94204

**Comment by Qengineering** [comment]
@mishabeliy15,

I noticed it also. I don't know what causes the download to fail. I worked the last months without any problem.
The only thing I can imagine is the number of downloads allowed. At this moment 200 visitors are downloading simultaneously the file. Please try it at a later moment.
If the issue persist, I will take proper action.

**Comment by mishabeliy15** [comment]
@Qengineering ,
I also can't download any partition of the splited image.

**Comment by Qengineering** [comment]
@mishabeliy15,

The link is working again. Let's assume it was the Sync server down for a moment.
Please contact if your still having trouble downloading

**Comment by Xilient** [comment]
I still having trouble downloading. Can you provide an alternative source for me? thx
