### ISSUE TITLE
whereis NVCC tha I can't find & operate with?

### ISSUE THREAD

**Issue by wir9** [Qengineering/Jetson-Nano-Ubuntu-20-image#49]
I see /usr/local/cuda-10.2, but "nvcc --version" has no response. Thanx in advance. But is very useful, that I can finally use Torch, my target. Thanx a lot. I wish to use .cu to compile in vscode,

**Comment by benjmerales** [comment]
Hi, let me help. Does using `nvcc -V` also not work?

**Comment by Qengineering** [comment]
Must work.
![Screenshot from 2023-10-23 09-28-50](https://github.com/Qengineering/Jetson-Nano-Ubuntu-20-image/assets/44409029/9179ee8e-4913-409e-a15f-a16f90baf471)

**Comment by wir9** [comment]
Not work.
One more thing.
Installed Intel wifi card, pasted iwil.deb to lib/firmware and keep not
working.
What I am doing badly?.
Thanx un advance

**Comment by Qengineering** [comment]
Sorry, that is the problem with many issues we received.
Everything works when deliverer. People start installing there software and get stocked.
Understandable, but (almost) impossible to debug.
I have really no clue. Something must have meshed with the Ubuntu/ NVIDIA folder structure.

**Comment by wir9** [comment]
Yes, that's I think, too
I was going to acquire a new Jetson orin nano, but due to the fails of this
Jetson nano I will not. I've seen that Intel 9461 is alright, but, why not
the rest???.
Thanx for your time and attention.
Have a nice day!.
nvcc -V only goes when root, not user $.
How should I solve this.
It implies not recognized in VA code Studio.
Sorry.
