### ISSUE TITLE
clone SD card to a bootable image file

### ISSUE THREAD

**Issue by sadidict** [Qengineering/Jetson-Nano-Ubuntu-20-image#53]
hi . i have a serious problem with cloning my 32 G sd card which has a lot of packages installed on it and i really can not have another bare image to prepare from scratch . 
can you please help me with cloning my sd card to a bootable file ? 
i know this is not totally related to this project but i use your image on my jetson and i thought you might help me with it . 
thank you sir/madam a lot

**Comment by fatemeh-mohseni-AI** [comment]
thank you a lot . I had a serious problem in this section too .
