### ISSUE TITLE
Any chance of updating kernel version to 5.6+?

### ISSUE THREAD

**Issue by plsnotracking** [Qengineering/Jetson-Nano-Ubuntu-20-image#56]
Hi, thank you for this amazing project, really appreciate it.

My quick question was about having a chance to upgrade the kernel to 5.6+, I'm trying to use wireguard, and seems like it's not working as intended in kernels sub 5.6, and in this case it's 4.9.

Any info with a workaround would be appreciated, thank you.

**Comment by Qengineering** [comment]
The Jetson Nano only supports kernels < 5, due to its limited CUDA support. Kernels above 4 require CUDA 11, which can't run on the Nano due to low-level driver dependencies. Sorry.

**Comment by plsnotracking** [comment]
I see, okay, thank you for the background.
