### ISSUE TITLE
jetson-io.py issue

### ISSUE THREAD

**Issue by SentryCoderDev** [Qengineering/Jetson-Nano-Ubuntu-20-image#67]
Hello, I installed your OS, but unfortunately I still have the same problem. When I run the 40 pin expansion header (jetson-io.py), it turns on and off for half a second.

Do you have a solution suggestion?

**Comment by Qengineering** [comment]
I'm sorry. I'm not familiar with jetson-io.py. 
Given the number of posts on the NVIDIA forum, it looks there are a lot of similar issues.
And all pretty low-level. Also with there solutions.
One thing for sure, it is not your hardware.

**Comment by SentryCoderDev** [comment]
Hello, after reinstalling it was fixed. Your OS will be very useful to me, thank you again.

**Comment by nick-pape** [comment]
I also am getting this issue, with the error stating that no APP partition was found (when it runs `
