### ISSUE TITLE
Very Slow Performance

### ISSUE THREAD

**Issue by adeljalalyousif** [Qengineering/Jetson-Nano-Ubuntu-20-image#74]
The Ubuntu image worked well (using a 64 GB SD card), but the Ubuntu system is very slow when installing certain libraries and packages such as Spyder IDE or others. The system appears to hang many times.
Additionally, the free space is only 4.6 GB, whereas the SD card has a capacity of 64 GB.

**Comment by Qengineering** [comment]
That's due to the Jetson Nano Quad-core ARM Cortex-A57.
It isn't fast. To be precise, with a clock of 1.4 GHz, it can be slower than a Raspberry Pi 4.
The great advantage of the Jetson family are their CUDA acceleration.
But CPU-wise, their are not the fastest in town.

**Comment by adeljalalyousif** [comment]
Is there a way to make this image (Ubuntu 20.04) faster ??
