### ISSUE TITLE
Tensor RT with Python 2.7

### ISSUE THREAD

**Issue by adeljalalyousif** [Qengineering/Jetson-Nano-Ubuntu-20-image#75]
How to import Tensor RT with Python 2.7??
I have used:
import tensorrt as trt
print("TensorRT Version:", trt.__version__)

and I got:
No module named tensorrt

**Comment by Qengineering** [comment]
Please take a look here:
https://docs.nvidia.com/deeplearning/tensorrt/api/python_api/
and
https://pypi.org/project/tensorrt/

**Comment by adeljalalyousif** [comment]
Thank you for your response.
Please can you respond to my previous issue: 'Very Slow Performance'.
