### ISSUE TITLE
Compatibility with SIM7600G-H 4G / 3G / 2G / GNSS module 

### ISSUE THREAD

**Issue by MarkHmnv** [Qengineering/Jetson-Nano-Ubuntu-20-image#81]
Is your image compatible with [SIM7600G-H 4G / 3G / 2G / GNSS module](https://www.waveshare.com/sim7600g-h-4g-for-jetson-nano.htm)?

**Comment by Qengineering** [comment]
No idea.
I've used the original Jetson Tegra image and upgraded the Ubuntu version.
If the modules work with the original Jetson Nano, the may work on this OS also.
But again, I never used them.
