### ISSUE TITLE
Image download not working

### ISSUE THREAD

**Issue by moiseshorta** [Qengineering/Jetson-Nano-Ubuntu-20-image#91]
Hello, 

Thanks for maintaining this project.

I'm having troubles downloading the latest image, as the download never starts.

Any help would be greatly appreciated.

Thank you!

**Comment by Qengineering** [comment]
I'm sorry to hear.
I've just tried the link and it is working fine over here.
Please try it later again. It should work.

**Comment by moiseshorta** [comment]
I dont have a problem downloading the Bare image, but rather the one with the preinstalled Pytorch, etc. packages.
