### ISSUE TITLE
Not a valid link to Sync for downloading the image

### ISSUE THREAD

**Issue by pvirvani** [Qengineering/Jetson-Nano-Ubuntu-20-image#92]
Hi,

I tried to download the image (both with ~10GB and ~6GB), but the links are not working.
There is server connection error with code 1000.

![image](https://github.com/user-attachments/assets/e462c5cd-bf95-43be-81b3-b1737dd1f0bb)

**Comment by Qengineering** [comment]
I've the same error on multiple Sync links. It seems the server is down. Please try later.

**Comment by g-r-a-e-m-e** [comment]
Currently downloading `JetsonNanoUb20_bare.img.xz` without issue. Thank y'all for having this image available.

**Comment by Qengineering** [comment]
You're welcome

**Comment by pvirvani** [comment]
Hi, the link is operational now, and the image was successfully downloaded.

**Comment by pvirvani** [comment]
Hi, the link is operational now, and the image was successfully downloaded.

Thanks for your quick response.
