### ISSUE TITLE
Broke Image Links

### ISSUE THREAD

**Issue by BeratTezer** [Qengineering/Jetson-Nano-Ubuntu-20-image#99]
Images files are not able to download from given resources. I need them as soons as possible. If somehow I can get them, I will make them reachable for everyone.

**Comment by BeratTezer** [comment]
I tried Waybak Machine snapshots but them also empty.

**Comment by BeratTezer** [comment]
This problem might be related with my locations, I will aslo try with VPN.

**Comment by Qengineering** [comment]
Indeed, location is the problem here. I've just tried to download the image and there is no problem whatsoever.
I will place a copy on Gdrive. Hopefully you can download it. It will take another hour before the upload of 9 GB is completed.....

**Comment by Qengineering** [comment]
Please find a copy at [GDrive](https://drive.google.com/file/d/1L2H_sQC_kSILrcJteWg7htKxJirtDsZ9/view?usp=sharing).

**Comment by BeratTezer** [comment]
Appreciate it. Thank you for your efforts 💖
